name: DServerExample
description: this is a server platform for dev to run server using Dart.
version: 1.0.0
author: Mohammed Fayez <fayezmohammed23@gmail.com>
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
